/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pomocna_aplikacija_jelvalcic_1;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jelvalcic
 */
public class GuiSlanjeKomandi extends javax.swing.JFrame {

    /**
     * Creates new form GuiSlanjeKomandi
     */
    public GuiSlanjeKomandi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTabovi = new javax.swing.JTabbedPane();
        tabAdmin = new javax.swing.JPanel();
        lblAdminKorIme = new javax.swing.JLabel();
        lblAdminLozinka = new javax.swing.JLabel();
        lblAdminKomanda = new javax.swing.JLabel();
        edAdminKorIme = new javax.swing.JTextField();
        edAdminLozinka = new javax.swing.JTextField();
        cmbAdminKomanda = new javax.swing.JComboBox();
        lblAdminZipKod = new javax.swing.JLabel();
        edAdminZipKod = new javax.swing.JTextField();
        tabKorisnik = new javax.swing.JPanel();
        lblKorisnikKorIme = new javax.swing.JLabel();
        lblKorisnikZipKod = new javax.swing.JLabel();
        edKorisnikKorIme = new javax.swing.JTextField();
        edKorisnikZipKod = new javax.swing.JTextField();
        edPort = new javax.swing.JTextField();
        lblPort = new javax.swing.JLabel();
        edServerIp = new javax.swing.JTextField();
        lblServerIp = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        edServerOdgovor = new javax.swing.JTextField();
        lblServerOdgovor = new javax.swing.JLabel();
        btnSloziKomandu = new javax.swing.JButton();
        lblKomandaComplete = new javax.swing.JLabel();
        edKomandaComplete = new javax.swing.JTextField();
        btnPosaljiKomandu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTabovi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                promjenaTaba(evt);
            }
        });

        lblAdminKorIme.setText("Korisnicko ime:");

        lblAdminLozinka.setText("Lozinka:");

        lblAdminKomanda.setText("Komanda:");

        cmbAdminKomanda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "START", "PAUSE", "STOP", "ADD ZIP", "TEST ZIP" }));
        cmbAdminKomanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAdminKomandaActionPerformed(evt);
            }
        });

        lblAdminZipKod.setText("Zip kod:");

        edAdminZipKod.setEditable(false);
        edAdminZipKod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edAdminZipKodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabAdminLayout = new javax.swing.GroupLayout(tabAdmin);
        tabAdmin.setLayout(tabAdminLayout);
        tabAdminLayout.setHorizontalGroup(
            tabAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdminKorIme)
                    .addComponent(lblAdminLozinka)
                    .addComponent(lblAdminKomanda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edAdminKorIme)
                    .addComponent(edAdminLozinka)
                    .addComponent(cmbAdminKomanda, 0, 119, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(lblAdminZipKod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edAdminZipKod, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        tabAdminLayout.setVerticalGroup(
            tabAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAdminLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(tabAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminKorIme)
                    .addComponent(edAdminKorIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(tabAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminLozinka)
                    .addComponent(edAdminLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(tabAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminKomanda)
                    .addComponent(cmbAdminKomanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminZipKod)
                    .addComponent(edAdminZipKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pnlTabovi.addTab("Administrator", tabAdmin);

        lblKorisnikKorIme.setText("Korisnicko ime:");

        lblKorisnikZipKod.setText("Zip kod:");

        javax.swing.GroupLayout tabKorisnikLayout = new javax.swing.GroupLayout(tabKorisnik);
        tabKorisnik.setLayout(tabKorisnikLayout);
        tabKorisnikLayout.setHorizontalGroup(
            tabKorisnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabKorisnikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabKorisnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKorisnikKorIme)
                    .addComponent(lblKorisnikZipKod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabKorisnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edKorisnikKorIme)
                    .addComponent(edKorisnikZipKod, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        tabKorisnikLayout.setVerticalGroup(
            tabKorisnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabKorisnikLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(tabKorisnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKorisnikKorIme)
                    .addComponent(edKorisnikKorIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(tabKorisnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKorisnikZipKod)
                    .addComponent(edKorisnikZipKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pnlTabovi.addTab("Korisnik", tabKorisnik);

        edPort.setText("10015");

        lblPort.setText("Port:");

        edServerIp.setText("127.0.0.1");

        lblServerIp.setText("Server IP:");

        edServerOdgovor.setEditable(false);

        lblServerOdgovor.setText("Odgovor servera:");

        btnSloziKomandu.setText("Slozi komandu");
        btnSloziKomandu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSloziKomanduActionPerformed(evt);
            }
        });

        lblKomandaComplete.setText("Komanda:");

        btnPosaljiKomandu.setText("Posalji");
        btnPosaljiKomandu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiKomanduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblServerIp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edServerIp, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edPort, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblServerOdgovor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edServerOdgovor))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKomandaComplete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edKomandaComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPosaljiKomandu)
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlTabovi, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSloziKomandu))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPort)
                    .addComponent(edServerIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServerIp))
                .addGap(52, 52, 52)
                .addComponent(pnlTabovi, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSloziKomandu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edKomandaComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKomandaComplete)
                    .addComponent(btnPosaljiKomandu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edServerOdgovor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServerOdgovor))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAdminKomandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAdminKomandaActionPerformed
        int komanda = cmbAdminKomanda.getSelectedIndex();

        if (komanda > 2) {
            edAdminZipKod.setEditable(true);
        } else {
            edAdminZipKod.setEditable(false);
        }
    }//GEN-LAST:event_cmbAdminKomandaActionPerformed

    private void btnSloziKomanduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSloziKomanduActionPerformed
        int tab;
        String komanda = "";
        tab = pnlTabovi.getSelectedIndex();

        if (tab == 0) {
            /*if(edAdminKorIme.getText().trim().length() > 2 && edAdminKorIme.getText().trim().length() < 11){
                
             }*/
            komanda = "USER " + edAdminKorIme.getText().trim() + "; PASSWD " + edAdminLozinka.getText().trim() + "; ";

            if (cmbAdminKomanda.getSelectedIndex() > 2) {
                String s1 = (String) cmbAdminKomanda.getSelectedItem();
                s1 = s1.trim();
                komanda = komanda + s1 + " " + edAdminZipKod.getText().trim() + ";";
            } else {
                String s2 = (String) cmbAdminKomanda.getSelectedItem();
                s2 = s2.trim();
                komanda = komanda + s2 + ";";
            }


        } else {
            komanda = "USER " + edKorisnikKorIme.getText().trim() + "; GET ZIP " + edKorisnikZipKod.getText().trim() + ";";
        }

        edKomandaComplete.setText(komanda);

    }//GEN-LAST:event_btnSloziKomanduActionPerformed

    private void promjenaTaba(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_promjenaTaba
        edKomandaComplete.setText("");
    }//GEN-LAST:event_promjenaTaba

    private void edAdminZipKodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edAdminZipKodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edAdminZipKodActionPerformed

    private void btnPosaljiKomanduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiKomanduActionPerformed
        String komanda = edKomandaComplete.getText();
        
        try {
            
            Socket server = new Socket(edServerIp.getText().trim(), Integer.parseInt(edPort.getText().trim()));
            OutputStream os = server.getOutputStream();
            InputStream is = server.getInputStream();
            os.write(komanda.getBytes());
            os.flush();
            server.shutdownOutput();

            StringBuilder odgovor = new StringBuilder();
            while (true) {
                int znak = is.read();
                if (znak == -1) {
                    break;
                }
                odgovor.append((char) znak);
            }

            edServerOdgovor.setText(odgovor.toString().trim());


            os.flush();
            os.close();
            is.close();
        } catch (UnknownHostException ex) {
            Logger.getLogger(GuiSlanjeKomandi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GuiSlanjeKomandi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPosaljiKomanduActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiSlanjeKomandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiSlanjeKomandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiSlanjeKomandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiSlanjeKomandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiSlanjeKomandi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPosaljiKomandu;
    private javax.swing.JButton btnSloziKomandu;
    private javax.swing.JComboBox cmbAdminKomanda;
    private javax.swing.JTextField edAdminKorIme;
    private javax.swing.JTextField edAdminLozinka;
    private javax.swing.JTextField edAdminZipKod;
    private javax.swing.JTextField edKomandaComplete;
    private javax.swing.JTextField edKorisnikKorIme;
    private javax.swing.JTextField edKorisnikZipKod;
    private javax.swing.JTextField edPort;
    private javax.swing.JTextField edServerIp;
    private javax.swing.JTextField edServerOdgovor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAdminKomanda;
    private javax.swing.JLabel lblAdminKorIme;
    private javax.swing.JLabel lblAdminLozinka;
    private javax.swing.JLabel lblAdminZipKod;
    private javax.swing.JLabel lblKomandaComplete;
    private javax.swing.JLabel lblKorisnikKorIme;
    private javax.swing.JLabel lblKorisnikZipKod;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblServerIp;
    private javax.swing.JLabel lblServerOdgovor;
    private javax.swing.JTabbedPane pnlTabovi;
    private javax.swing.JPanel tabAdmin;
    private javax.swing.JPanel tabKorisnik;
    // End of variables declaration//GEN-END:variables
}
